name: Sync to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://huggingface.co/spaces/my984/recommendation-job hf_space
          rsync -av --exclude=.git ./ hf_space/
          cd hf_space
          git add .
          git commit -m "Update Space" || true
          git push